name: 'Trigger Workflow and Wait - Composite Action'
description: 'This action triggers a workflow in another repository and waits for the result.'
author: 'joshjohanning'
branding:
  icon: 'arrow-right'
  color: 'yellow'
inputs:
  owner:
    description: "The owner of the repository where the workflow is contained."
    required: true
  repo:
    description: "The repository where the workflow is contained."
    required: true
  github_token:
    description: "The Github access token with access to the repository. It is recommended you put this token under secrets."
    required: false
  github_user:
    description: "The name of the github user whose access token is being used to trigger the workflow."
    required: false
  ref:
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA. Default: main'
    required: false
  wait_interval:
    description: "The number of seconds delay between checking for result of run."
    default: '10'
    required: false
  workflow_file_name:
    description: "The reference point. For example, you could use main.yml."
    required: true
  client_payload:
    description: 'Payload to pass to the workflow, must be a JSON string'
    required: false
  propagate_failure:
    description: 'Fail current job if downstream job fails. default: true'
    required: false
  trigger_workflow:
    description: 'Trigger the specified workflow. default: true'
    required: false
  wait_workflow:
    description: 'Wait for workflow to finish. default: true'
    required: false
  comment_downstream_url:
    description: 'Comment API link for commenting the downstream job URL'
    required: false
    default: ''
  comment_github_token:
    description: "The Github access token with access to the repository for comment URL. It is recommended you put this token under secrets."
    required: false
    default: ${{ github.token }}
  github_app_id:
    description: "If you are using a GitHub App, you can provide the App ID here and we will generate the token. NOTE: This is only used if github_token is not provided."
    required: false
  github_app_installation_id:
    description: "If you are using a GitHub App, you can provide the Installation ID here and we will generate the token. NOTE: This is only used if github_token is not provided."
    required: false
  github_app_private_key:
    description: "If you are using a GitHub App, you can provide the Private Key secret value here and we will generate the token. NOTE: This is only used if github_token is not provided."
    required: false
outputs:
  workflow_id:
    description: The ID of the workflow that was triggered by this action
    value: ${{ steps.trigger-workflow-and-wait.outputs.workflow_id }}
  workflow_url:
    description: The URL of the workflow that was triggered by this action
    value: ${{ steps.trigger-workflow-and-wait.outputs.workflow_url }}
  conclusion:
    description: Conclusion of the job, i.e pass/failure
    value: ${{ steps.trigger-workflow-and-wait.outputs.conclusion }}
runs:
  using: 'composite'
  steps:
    # TODO: remove this dependency
    - name: install gh-token
      run: gh extension install link-/gh-token
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Trigger Workflow and Wait
      run: ${{ github.action_path }}/script.sh
      id: trigger-workflow-and-wait
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GITHUB_USER: ${{ inputs.github_user }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_WAIT_INTERVAL: ${{ inputs.wait_interval }}
        INPUT_WORKFLOW_FILE_NAME: ${{ inputs.workflow_file_name }}
        INPUT_CLIENT_PAYLOAD: ${{ inputs.client_payload }}
        INPUT_PROPAGATE_FAILURE: ${{ inputs.propagate_failure }}
        INPUT_TRIGGER_WORKFLOW: ${{ inputs.trigger_workflow }}
        INPUT_WAIT_WORKFLOW: ${{ inputs.wait_workflow }}
        INPUT_COMMENT_DOWNSTREAM_URL: ${{ inputs.comment_downstream_url }}
        INPUT_COMMENT_GITHUB_TOKEN: ${{ inputs.comment_github_token }}
        INPUT_GITHUB_APP_ID: ${{ inputs.github_app_id }}
        INPUT_GITHUB_APP_INSTALLATION_ID: ${{ inputs.github_app_installation_id }}
        INPUT_GITHUB_APP_PRIVATE_KEY: ${{ inputs.github_app_private_key }}
