name: 'Trigger Workflow and Wait - Composite Action'
description: 'This action triggers a workflow in another repository and waits for the result.'
author: 'joshjohanning'
branding:
  icon: 'arrow-right'
  color: 'yellow'
inputs:
  owner:
    description: "The owner of the repository where the workflow is contained."
    required: true
  repo:
    description: "The repository where the workflow is contained."
    required: true
  github_token:
    description: "The Github access token with access to the repository. It is recommended you put this token under secrets."
    required: true
  github_user:
    description: "The name of the github user whose access token is being used to trigger the workflow."
    required: false
  ref:
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA. Default: main'
    required: false
  wait_interval:
    description: "The number of seconds delay between checking for result of run."
    required: false
  workflow_file_name:
    description: "The reference point. For example, you could use main.yml."
    required: true
  client_payload:
    description: 'Payload to pass to the workflow, must be a JSON string'
    required: false
  propagate_failure:
    description: 'Fail current job if downstream job fails. default: true'
    required: false
  trigger_workflow:
    description: 'Trigger the specified workflow. default: true'
    required: false
  wait_workflow:
    description: 'Wait for workflow to finish. default: true'
    required: false
  comment_downstream_url:
    description: 'Comment API link for commenting the downstream job URL'
    required: false
    default: ''
  comment_github_token:
    description: "The Github access token with access to the repository for comment URL. It is recommended you put this token under secrets."
    required: false
    default: ${{ github.token }}
outputs:
  workflow_id:
    description: The ID of the workflow that was triggered by this action
    value: ${{ steps.trigger-workflow-and-wait.outputs.workflow_id }}
  workflow_url:
    description: The URL of the workflow that was triggered by this action
    value: ${{ steps.trigger-workflow-and-wait.outputs.workflow_url }}
  conclusion:
    description: Conclusion of the job, i.e pass/failure
    value: ${{ steps.trigger-workflow-and-wait.outputs.conclusion }}
runs:
  using: 'composite'
  steps:
    - name: Trigger Workflow and Wait
      run: ${{ github.action_path }}/script.sh
      id: trigger-workflow-and-wait
      shell: bash
      env:
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        github_token: ${{ inputs.github_token }}
        github_user: ${{ inputs.github_user }}
        ref: ${{ inputs.ref }}
        wait_interval: ${{ inputs.wait_interval }}
        workflow_file_name: ${{ inputs.workflow_file_name }}
        client_payload: ${{ inputs.client_payload }}
        propagate_failure: ${{ inputs.propagate_failure }}
        trigger_workflow: ${{ inputs.trigger_workflow }}
        wait_workflow: ${{ inputs.wait_workflow }}
        comment_downstream_url: ${{ inputs.comment_downstream_url }}
        comment_github_token: ${{ inputs.comment_github_token }}
